{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smithd.secretName" . }}
  labels:
    {{- include "smithd.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.secrets.apiKeys | quote }}
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | quote }}
  gitops-ssh-key: {{ .Values.secrets.gitopsSshKey | quote }}
{{- end }}
